// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC26BSAnkM72vFnb4fEL5ITmQQiMUxYCpE',
    appId: '1:878211431258:web:cc9d2dcfa578abfeeb9163',
    messagingSenderId: '878211431258',
    projectId: 'waddahapp-828fa',
    authDomain: 'waddahapp-828fa.firebaseapp.com',
    storageBucket: 'waddahapp-828fa.firebasestorage.app',
    measurementId: 'G-9DPMD1B30C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG5jbWNFaKG5RGdfCbqWNHdo5Z7C0OE5w',
    appId: '1:878211431258:android:da234f2d761ea745eb9163',
    messagingSenderId: '878211431258',
    projectId: 'waddahapp-828fa',
    storageBucket: 'waddahapp-828fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaOTry6Ni3LFJ4mnKiAYZuG5tDhmpVc0',
    appId: '1:878211431258:ios:62b5658bcaf16fc6eb9163',
    messagingSenderId: '878211431258',
    projectId: 'waddahapp-828fa',
    storageBucket: 'waddahapp-828fa.firebasestorage.app',
    iosBundleId: 'com.example.waddahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIaOTry6Ni3LFJ4mnKiAYZuG5tDhmpVc0',
    appId: '1:878211431258:ios:62b5658bcaf16fc6eb9163',
    messagingSenderId: '878211431258',
    projectId: 'waddahapp-828fa',
    storageBucket: 'waddahapp-828fa.firebasestorage.app',
    iosBundleId: 'com.example.waddahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC26BSAnkM72vFnb4fEL5ITmQQiMUxYCpE',
    appId: '1:878211431258:web:f090dfde66c9f315eb9163',
    messagingSenderId: '878211431258',
    projectId: 'waddahapp-828fa',
    authDomain: 'waddahapp-828fa.firebaseapp.com',
    storageBucket: 'waddahapp-828fa.firebasestorage.app',
    measurementId: 'G-JPFE2T74WE',
  );
}
